channels:
- conda-forge
dependencies:
- astropy=4.3.1
- bilby=1.1.5
- corner=2.2.1
- gwosc=0.5.4
- gwpy=2.1.3
- h5py=3.6.0
- ipykernel=6.9.0
- ipython=8.0.1
- jupyter_client=7.1.2
- jupyter_console=6.4.0
- jupyter_core=4.9.1
- lalsuite=7.3
- ligo.skymap=0.5.3
- matplotlib=3.4.3
- notebook=6.4.8
- numpy=1.20.3
- pandas=1.4.0
- pip=22.0.3
- pycbc=2.0.1
- pygcn=1.0.2
- python=3.9.10
- scipy=1.8.0
- wget=1.20.3
name: igwn-py39-lw
