name: Run the code

on:
  push:
    branches: "*"

jobs:
  day1:
    name: Day 1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-python@v2
    - name: Create and activate the environment
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        for file in Tutorials/Day_1/*ipynb; do echo $file; $CONDA/bin/jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $file; done
        for file in Tutorials/Day_1/*ipynb; do echo $file; $CONDA/bin/jupyter nbconvert --to notebook --execute $file; done
