name: Run the code

on:
  push:
    branches: "*"

jobs:
  day1:
    name: Day 1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Create and activate the environment
      run: |
        conda env create -f environment.yml
        conda activate igwn-py39-lw || true
        for file in Tutorials/Day_1/*ipynb; do echo $file; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $file; done
        for file in Tutorials/Day_1/*ipynb; do echo $file; jupyter nbconvert --to notebook --execute $file; done
