name: Run the code

on:
  push:
    branches: "*"

jobs:
  Day1:
    name: Day 1 Tutorials
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install pandoc
    - name: Execute and convert
      run: |
        for file in Tutorials/Day_1/*ipynb; do jupyter nbconvert --to html $file --execute; done
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: HTML-Day1
        path: Tutorials/Day_1/*html

  Day2:
    name: Day 2 Tutorials
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install pandoc
    - name: Execute and convert
      run: |
        for file in Tutorials/Day_2/*ipynb; do jupyter nbconvert --to html $file --execute; done
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: HTML-Day2
        path: Tutorials/Day_2/*html

  Day3:
    name: Day 3 Tutorials
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install pandoc
    - name: Execute and convert
      run: |
        for file in Tutorials/Day_3/*ipynb; do jupyter nbconvert --to html $file --execute; done
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: HTML-Day3
        path: Tutorials/Day_3/*html
