name: Run the code

on:
  push:
    branches: "*"

jobs:
  t11:
    name: Tutorials 1.1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Create and activate the environment
      run: |
        file=Tuto_1.1_Discovering_Open_Data.ipynb
        echo $file
