name: Run the code

on:
  push:
    branches: "*"

jobs:
  t11:
    name: Tutorials 1.1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Create and activate the environment
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        file=Tutorials/Day_1/Tuto_1.1_Discovering_Open_Data.ipynb
        echo $file
        $CONDA/bin/jupyter nbconvert --to python $file
        $CONDA/bin/python $file
