name: Spelling check

on:
  push:
    branches: "*"

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Test with codespell
      run: |
        python -m pip install -U pip
        python -m pip install -U jupyter codespell
        ls
        #for file in Tutorials/Day_*/*ipynb; do echo $file; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace $file; done
        codespell . --ignore-regex "\b[a-zA-Z]{2,3}\b" -I .dictionary.txt
