name: Spelling check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Test with codespell
      run: |
        codespell . --ignore-regex "\b[a-zA-Z]{2,3}\b"
